name: farmhouse_booking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1                      # State management
  http: ^1.2.1                          # REST API calls
  fluttertoast: ^8.2.2                 # Toast messages
  shared_preferences: ^2.2.2            # Local storage (login/session)
  intl: ^0.18.1                        # Date formatting

  google_maps_flutter: ^2.5.3
  geolocator: ^12.0.0
  geocoding: ^2.2.0

  image_picker: ^1.0.7                  # Pick images from gallery/camera
  cached_network_image: ^3.3.1          # Image caching for faster loading

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  firebase_storage: ^11.6.0
  url_launcher: ^6.2.5
  
  razorpay_flutter: ^1.3.5              # Razorpay integration (India-based)

  flutter_spinkit: ^5.2.0               # Loading animations
  animations: ^2.0.11                   # Pre-built transition animations

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #assets:
  #  - assets/images/
   # - assets/icons/
